FROM ubuntu

# Install Docker
RUN apt-get update && \
    apt-get install -y curl &&\
    curl -sSL https://get.docker.com/ | sh -e

# Install flexible io tester
RUN apt-get update && \
    apt-get install -y fio

# Set custom entrypoint to start Docker daemon in the container
COPY ubuntu-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

