#!/bin/bash

source "${BASH_SOURCE%/*}/../../utils/logManager"

ensure_docker() {
	isDockerInstalled=`docker --version | grep -c ^"Docker version"`
	if [ "$isDockerInstalled" -eq 1 ];
	then 
		dockerIsRunning=`docker ps | grep -c "CONTAINER ID"`
		if [ "$dockerIsRunning" -eq 1 ];
		then 
			logThis "Docker is up and running" "SUCCESS"
		else
			logThis "Docker is not running" "ERROR"
		fi
	else
		logThis "Docker is not installed" "ERROR"
	fi
}