#!/bin/bash

source "${BASH_SOURCE%/*}/../../utils/logManager"


isOpenShiftInstalled=`oc version | grep -c ^"oc"`
if [ "$isOpenShiftInstalled" -eq 1 ]; 
then 
	logThis "openShift is running" "SUCCESS"
	k8sVersion=`oc version | grep "kubernetes" | cut -d ' ' -f2`
	logThis "Kubernetes version is $k8sVersion" "INFO"
	ocVersion=`oc version | grep "oc" | cut -d ' ' -f2`
	logThis "OpenShift version is $ocVersion" "INFO"
else
	logThis "OpenShift is not installed" "ERROR"
fi