FROM golang:1.21-alpine
LABEL MAINTAINER CyberArk Software Ltd.
LABEL id="conjur-inspect-test-runner"

# On CyberArk dev laptops, golang module dependencies are downloaded with a
# corporate proxy in the middle. For these connections to succeed we need to
# configure the proxy CA certificate in build containers.
#
# To allow this script to also work on non-CyberArk laptops where the CA
# certificate is not available, we copy the (potentially empty) directory
# and update container certificates based on that, rather than rely on the
# CA file itself.
ADD build_ca_certificate /usr/local/share/ca-certificates/
RUN update-ca-certificates

WORKDIR /conjur-inspect

RUN apk update && apk upgrade --no-cache libcrypto3
RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY go.mod go.sum /conjur-inspect/

RUN go mod download

COPY . .

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m" ]
