version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    working_dir: /conjur-inspect
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/conjur-inspect
