#!/bin/bash -e
source "${BASH_SOURCE%/*}/../../utils/logManager"


function checkCpu() {
	amountOfCpu=`sysctl hw.ncpu | grep "hw.ncpu:" | cut -d ' ' -f2`
	minCpu="4"
	if [ "$amountOfCpu" -gt "$minCpu" ];
	then 
		logThis "Amount of CPUs is good $amountOfCpu" "SUCCESS"
	else
		logThis "CPU count is less than 4" "ERROR"
	fi
}