#!/bin/bash -e
source ../../utils/PrintMessage.sh


amountOfMem=`sysctl hw.memsize | grep "hw.memsize:" | cut -d ' ' -f2`
MinMem="4046583"
if [ "$amountOfMem" -gt "$MinMem" ];
then 
	success_message "Memory amount is good $amountOfMem"
else
	fail_message "Memory amount less than 4GB"
fi