#!/bin/bash -e
source "${BASH_SOURCE%/*}/../../utils/logManager"

function checkMemory() {
	amountOfMem=`sysctl hw.memsize | grep "hw.memsize:" | cut -d ' ' -f2`
	MinMem="4046583"
	if [ "$amountOfMem" -gt "$MinMem" ];
	then 
		logThis "Memory amount is good $amountOfMem" "SUCCESS"
	else
		logThis "Memory amount less than 4GB" "ERROR"
	fi
}