#!/bin/bash

source ./environment

# This should echo that "TEST" is not set and use the "<value>" recommendation
ensure_environment "TEST"

# This should echo that TEST is not set and use the recommendation "My variable"
ensure_environment "TEST" "\"My variable\""

# This should echo that the TEST2 variable is defined
export TEST2="test"
ensure_environment "TEST2"