#!/bin/bash -e
# logManager util
#
# Enable easy logging framework for bash
# e.g: logThis "This will log" "WARN" and script_logging_level="WARN"
#

source "${BASH_SOURCE%/*}/../utils/formatting"

DEBUG=0;
INFO=1;
SUCCESS=2;
WARN=3;
ERROR=4;
FATAL=5;

logThis()
{
    local log_message=$1
    local log_priority=$2

    #check if level exists
    [[ ${!log_priority} ]] || return 1

    #check if level is enough
    (( ${!log_priority} < ${!script_logging_level} )) && return 2

    #log here
	if [ ${!log_priority} -gt 2 ]; then
	   printf "${BOLD}${RED}${log_priority} - ${log_message} ${NORMAL}\n"
	elif [ ${!log_priority} -eq 2 ]; then
	   printf "${NORMAL}${GREEN}${log_priority} - ${log_message} ${NORMAL}\n"
    else
       printf "${NORMAL}${log_priority} - ${log_message}\n"
	fi  
}