#!/bin/bash -e
source "${BASH_SOURCE%/*}/../../utils/logManager"

# Connectivity module

# Check given URL status is valid or not
# $1 - URL
is_url_reachable()
{
	variable_name=$1
	script_logging_level="DEBUG"

	if [ -z ${variable_name} ]; then 
		logThis "You did not secifiy a URL" "ERROR"
	else
		logThis "Check URL $1 reachable" "DEBUG"
		echo curl -s --head $1 | head -n 1 | grep "HTTP/1.[01] [23].."
	fi
}

# $1 - Server IP
# $2 - Port
ensure_port()
{
	local result=$(nc -v -w 1 -G 1 $1 $2 2>&1)
	local success=$(echo $result | grep 'succeeded')

	if [[ -z $1 ]]; then 
		logThis "You did not secifiy a host name or IP address" "ERROR"
		return
	fi

	if [[ -z ${success} ]]; then 
		logThis "Could not access '$1' on port $2" "ERROR"
	else
		logThis "Port $2 at '$1' is open and reachable" "SUCCESS"
	fi
}
