#!/bin/bash -e
# Connectivity module
#
# The Connectivity modules provides check for network connectivity issues
# focus on URL and ports

source "${BASH_SOURCE%/*}/../../utils/logManager"

# Check given URL status is valid or not
# $1 - URL
is_url_reachable()
{
	supplied_url=$1
	script_logging_level="DEBUG"
	if [ -z ${supplied_url} ]; then 
		logThis "You did not secifiy a URL" "ERROR"
	else
		if curl --output /dev/null --silent --head --fail "${supplied_url}";
		then
			logThis "Supplied URL '$supplied_url' reachable" "SUCCESS"
		else
			logThis "Supplied URL '$supplied_url' is not reachable" "ERROR"
		fi
	fi
}

# Check given server and port are open for communication
# $1 - Server IP
# $2 - Port
ensure_port()
{
	local result=$(nc -v -w 1 -G 1 $1 $2 2>&1)
	local success=$(echo $result | grep 'succeeded')

	if [[ -z $1 ]]; then 
		logThis "You did not secifiy a host name or IP address" "ERROR"
		return
	fi

	if [[ -z ${success} ]]; then 
		logThis "Could not access '$1' on port $2" "ERROR"
	else
		logThis "Port $2 at '$1' is open and reachable" "SUCCESS"
	fi
}
