#!/bin/bash -e
### Start configuration ###
script_logging_level="INFO"
### End configuration ###


source "${BASH_SOURCE%/*}/../modules/os/checkCpu"
source "${BASH_SOURCE%/*}/../modules/os/checkMemory"
source "${BASH_SOURCE%/*}/../modules/os/environment"
source "${BASH_SOURCE%/*}/../modules/docker/docker"
source "${BASH_SOURCE%/*}/../modules/network/connectivity"
source "${BASH_SOURCE%/*}/../modules/openshift/checkDockerVersion"

# Verify machine resources
echo "--------------------------"
echo "Checking machine resources"
echo "--------------------------"
checkMemory
checkCpu

# Verify Client

# - Client Environment Variables
echo
echo "----------------------------------"
echo "Checking environment configuration"
echo "----------------------------------"
ensure_environment "OSHIFT_CLUSTER_ADMIN_USERNAME" "cadmin"
ensure_environment "OSHIFT_CONJUR_ADMIN_USERNAME" "cadmin"
ensure_environment "CONJUR_NAMESPACE_NAME" "conjur-cluster-5-1-2" # can be set to anything
ensure_environment "CONJUR_APPLIANCE_IMAGE" "registry2.itci.conjur.net/conjur-appliance:5.1.2"
ensure_environment "CONJUR_ACCOUNT" "conjur-account"
ensure_environment "CONJUR_ADMIN_PASSWORD" "SuperSecret"
ensure_environment "CONJUR_VERSION" "5"
ensure_environment "DOCKER_REGISTRY_PATH" "openshift-39.itci.conjur.net"
ensure_environment "PLATFORM" "openshift"
ensure_environment "AUTHENTICATOR_ID" "conjur-authn" # should be set to unique string

# - Docker installed, Version, and Availability
#     - Registry Configured (either be secure, or add to insecure registries)
# - Conjur Appliance Image Exists and Version
echo
echo "-----------------------------"
echo "Checking docker configuration"
echo "-----------------------------"
ensure_docker
docker_image_exists "haproxy:1.8"
docker_image_exists "${CONJUR_APPLIANCE_IMAGE}"
docker_image_exists "cyberark/conjur-cli:5"

# - Registry Network Access

#ensure_network_access($(OPENSHIFT_MASTER_HOST))

# - Openshift Client Installed and Version

#ensure_program("oc")

# - Can connect to cluster


# Verify Cluster
# - Cluster/openshift version
# - Infrastructure (Disk, Memory, CPU)
# - Ports Open
echo
echo "-------------------------------------"
echo "Checking cluster network connectivity"
echo "-------------------------------------"
ensure_port "$DOCKER_REGISTRY_PATH" 80
ensure_port "$DOCKER_REGISTRY_PATH" 443
ensure_port "$DOCKER_REGISTRY_PATH" 22
#     - 80 & 443 for Conjur API and UI
#     - 22 for SSH
#     - 8443 for Openshift UI
