---

name: goreleaser

on:
  # Run this on pushes to any branch
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          install-only: true
      - name: Run GoReleaser
        run: GORELEASER_CURRENT_TAG=v0.0.0 goreleaser release --snapshot --rm-dist
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/binaries/*
